substitutions:
  _REGION: us-central1
steps:
- name: 'gcr.io/k8s-skaffold/skaffold'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Build and push images
    skaffold build --file-output=/workspace/artifacts.json \
                   --default-repo gcr.io/$PROJECT_ID \
                   --push=true

    # Test images
    skaffold test --build-artifacts=/workspace/artifacts.json
