steps:
- name: golang:1.11
  entrypoint: bash
  args:
  - -c
  - |
    cd /workspace
    go test
- name: gcr.io/$PROJECT_ID/skaffold:alpha
  args: ['run', '-f=skaffold.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=staging'
