apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: sample-app
build:
  artifacts:
  - image: go-mod-image
deploy:
  kustomize:
    paths: ["."]
portForward:
- resourceType: service
  resourceName: go-mod-image
  port: 8080
