apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: backend
requires:
  - path: validate/
build:
  artifacts:
  - image: sample-app
test:
  - image: sample-app
    custom:
    - command: docker run $IMAGE go test
deploy:
  kubectl:
    manifests: ["k8s/dev.yaml"]
profiles:
- name: prod
  deploy:
    kubectl:
      manifests: ["k8s/prod.yaml"]
portForward:
  - resourceName: sample-app-dev
    resourceType: service
    namespace: default
    port: 8080