apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: backend
requires:
  - path: validate/
build:
  artifacts:
  - image: sample-app
test:
  - image: sample-app
    custom:
    - command: docker run $IMAGE go test
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
portForward:
  - resourceName: sample-app-dev
    resourceType: service
    namespace: default
    port: 8080