apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: sample-app
test:
  - image: sample-app
    custom:
    # Specify absolute path of your K8s folder to mount to validation image
    - command: docker run -v /Users/abbycar/Documents/code/sample-app:/k8s gcr.io/abbycar-project/test-validate-image:latest
deploy:
  kubectl:
    manifests: ["k8s/dev.yaml"]
profiles:
- name: prod
  deploy:
    kubectl:
      manifests: ["k8s/prod.yaml"]
portForward:
  - resourceName: sample-app-dev
    resourceType: service
    namespace: default
    port: 8080