apiVersion: skaffold/v1alpha3
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: gcr.io/vic-bin-authz-0/gceme
deploy:
  kubectl:
    manifests:
    - k8s/dev/*
    - k8s/services/*
