kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: backend
      labels:
        env: production
    spec:
      containers:
      - name: sample-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: VERSION
          value: production
        - name: REDIS_URL
          value: 172.30.0.11:6379
