apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: sample-app
      name: sample-app
    spec:
      containers:
      - env:
        - name: VERSION
          value: dev
        - name: REDIS_URL
          value: redis:6379
        image: viglesiasce/sample-app
        imagePullPolicy: IfNotPresent
        name: sample-app
        ports:
        - containerPort: 8080
          name: sample-app
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
  
