apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-getter-dev
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-pods-dev
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-getter-dev
subjects:
- kind: ServiceAccount
  name: default
