apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-getter
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-pods
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-getter
subjects:
- kind: ServiceAccount
  name: default
