apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: sample-app
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      containers:
      - command:
        - redis-server
        env:
        - name: MASTER
          value: "true"
        image: redis:5.0.4
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.3"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
      - emptyDir: {}
        name: data
