kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      env: canary
  template:
    metadata:
      name: sample-app
      labels:
        env: canary
    spec:
      containers:
      - name: sample-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: VERSION
          value: canary
        - name: REDIS_URL
          value: 172.30.0.11:6379
