substitutions:
  _REGION: us-central1
steps:
- name: 'gcr.io/k8s-skaffold/skaffold:v1.24.0'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    go test
    docker build -t gcr.io/$PROJECT_ID/sample-app-backend:$SHORT_SHA .

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set api_endpoint_overrides/clouddeploy "https://staging-clouddeploy.sandbox.googleapis.com/"
    gcloud alpha deploy apply --file ci-cd/deploy.yaml --region ${_REGION}
    gcloud alpha deploy releases create $(date +%s) \
                        --delivery-pipeline web-app \
                        --region ${_REGION} \
                        --image sample-app-backend=gcr.io/$PROJECT_ID/sample-app-backend:$SHORT_SHA
