name: Continuous Integration
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
  build-and-push:
    # Don't do this for pull requests, only on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:${{ github.sha }}
  deploy:
    needs: [ build-and-push ]
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout manifests'
      uses: actions/checkout@v2
      with:
        repository: viglesiasce/sample-app-manifests
        token: ${{ github.token }}
        path: sample-app-manifests
    - name: Update manifests
      run: |
           git config --global user.name ${GITHUB_ACTOR}
           git config --global user.email ${GITHUB_ACTOR}@vic.dev
           cp k8s-manifests/* sample-app-manifests/
           cd sample-app-manifests/
           git add .
           git commit -m "Deploying version $GITHUB_SHA"
           git push origin master
